name: flutter_markdown
author: Flutter Authors <flutter-dev@googlegroups.com>
description: A markdown renderer for Flutter.
homepage: https://github.com/flutter/flutter_markdown
version: 0.1.2

dependencies:
  flutter:
    sdk: flutter
  markdown: ^1.0.0
  meta: ^1.0.5
  string_scanner: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: '>=1.19.0 <2.0.0'
